# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9aa70291a9b6be4093888e60ff9b02b621fa688d341e11b06e3a06c8bed9db7a8240fec3f51ba7c979729187de6c600ed03f7abd7539ae9631aa8e20afebcf99

test:
  secret_key_base: 0fd85c29c7b243bc879293727872f23dcc9bb61de060858b9ebbe19faffea1827756741937e682a03e4c79367215a514c5127337dbafc5ae8185476b41b574ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
